// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Categories struct {
	ID   *string `json:"ID"`
	Name *string `json:"name"`
}

type Chapters struct {
	ID      *string `json:"ID"`
	Name    *string `json:"name"`
	MangaID *string `json:"manga_id"`
}

type GetAllMangasResponse struct {
	CreatedAt   *string `json:"CreatedAt"`
	UpdatedAt   *string `json:"UpdatedAt"`
	DeletedAt   *string `json:"DeletedAt"`
	ID          *string `json:"ID"`
	Name        *string `json:"name"`
	Thumbnail   *string `json:"thumbnail"`
	Description *string `json:"description"`
}

type GetMangaDetailsResponse struct {
	CreatedAt   *string       `json:"CreatedAt"`
	UpdatedAt   *string       `json:"UpdatedAt"`
	DeletedAt   *string       `json:"DeletedAt"`
	ID          *string       `json:"ID"`
	Name        *string       `json:"name"`
	Thumbnail   *string       `json:"thumbnail"`
	Description *string       `json:"description"`
	Chapters    []*Chapters   `json:"chapters"`
	Categories  []*Categories `json:"categories"`
}
