// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Chapter struct {
	ID      *string `json:"id"`
	Name    *string `json:"name"`
	Pages   *string `json:"pages"`
	MangaID *string `json:"mangaId"`
}

type Manga struct {
	ID          *string    `json:"id"`
	Name        *string    `json:"name"`
	Thumbnail   *string    `json:"thumbnail"`
	Description *string    `json:"description"`
	Chapters    []*Chapter `json:"chapters"`
}
