// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Categories struct {
	ID   *string `json:"ID"`
	Name *string `json:"name"`
}

type Chapters struct {
	ID      *string `json:"ID"`
	Name    *string `json:"name"`
	MangaID *string `json:"manga_id"`
}

type GetAllMangasResponse struct {
	CreatedAt   *string       `json:"CreatedAt"`
	UpdatedAt   *string       `json:"UpdatedAt"`
	DeletedAt   *string       `json:"DeletedAt"`
	ID          *string       `json:"ID"`
	Name        *string       `json:"name"`
	Thumbnail   *string       `json:"thumbnail"`
	Description *string       `json:"description"`
	Categories  []*Categories `json:"categories"`
}

type GetChapterResponse struct {
	CreatedAt *string  `json:"CreatedAt"`
	UpdatedAt *string  `json:"UpdatedAt"`
	DeletedAt *string  `json:"DeletedAt"`
	ID        *string  `json:"ID"`
	Name      *string  `json:"name"`
	MangaID   *string  `json:"manga_id"`
	Pages     []*Pages `json:"pages"`
}

type GetMangaDetailsResponse struct {
	CreatedAt   *string     `json:"CreatedAt"`
	UpdatedAt   *string     `json:"UpdatedAt"`
	DeletedAt   *string     `json:"DeletedAt"`
	ID          *string     `json:"ID"`
	Name        *string     `json:"name"`
	Thumbnail   *string     `json:"thumbnail"`
	Description *string     `json:"description"`
	Chapters    []*Chapters `json:"chapters"`
}

type Pages struct {
	ID        *string `json:"ID"`
	URL       *string `json:"url"`
	ChapterID *string `json:"chapter_id"`
}
